<a href="https://colab.research.google.com/github/noreenlaigo/ACTIVITIES/blob/main/Module_6_Act.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Noreen Laigo

In [1]:
for fizzbuzz in range(20):
    if fizzbuzz % 3 == 0 and fizzbuzz % 5 == 0:
        print("fizzbuzz")
        continue
    elif fizzbuzz % 3 == 0:
        print("fizz")
        continue
    elif fizzbuzz % 5 == 0:
        print("buzz")
        continue
    print(fizzbuzz)

fizzbuzz
1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19


Bakery NumPy Exercise

In [4]:
quantity_sold=[17,40,1]
type(quantity_sold)

list

In [5]:
price=[2,1,10]
type(price)

list

In [9]:
import numpy as np

In [10]:
price_array=np.array(price)
quantity_sold_array=np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [11]:
price_array* quantity_sold_array

array([34, 40, 10])

In [12]:
price_array=price_array+[7]
print(price_array)

[ 9  8 17]


In [13]:
price_array=price_array-[7]

price_array=np.append(price_array,7)
print(price_array)

[ 2  1 10  7]


In [14]:
price * quantity_sold_array

array([34, 40, 10])

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd

In [15]:
filename = '/content/bostonHousing1978.csv'
df = pd.read_csv(filename)

df.head()

RM  LSTAT  PTRATIO  target
0  6.575   4.98     15.3    24.0
1  6.421   9.14     17.8    21.6
2  7.185   4.03     17.8    34.7
3  6.998   2.94     18.7    33.4
4  7.147   5.33     18.7    36.2

In [23]:
import pandas as pd
df= pd.read_csv('https://raw.githubusercontent.com/mGalarnyk/Tutorial_Data/master/Pandas/CalIt2.data')

In [24]:
df = pd.read_csv('https://raw.githubusercontent.com/mGalarnyk/Tutorial_Data/master/Pandas/CalIt2.data')

df.head()

7  07/24/05  00:00:00  0
0  9  07/24/05  00:00:00  0
1  7  07/24/05  00:30:00  1
2  9  07/24/05  00:30:00  0
3  7  07/24/05  01:00:00  0
4  9  07/24/05  01:00:00  0

In [25]:
df = pd.read_csv('https://raw.githubusercontent.com/mGalarnyk/Tutorial_Data/master/Pandas/CalIt2.data', header = None)

df.head()

0         1         2  3
0  7  07/24/05  00:00:00  0
1  9  07/24/05  00:00:00  0
2  7  07/24/05  00:30:00  1
3  9  07/24/05  00:30:00  0
4  7  07/24/05  01:00:00  0